# Generated by Django 5.0 on 2025-09-21 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='anexos_historicos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('trimestre', models.CharField(max_length=20)),
                ('anexo_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anexorequerido')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
