# Generated by Django 5.0 on 2025-04-11 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('aprobado', '✅ Aprobado'), ('rechazado', '❌ Rechazado')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
