# Generated by Django 5.0 on 2025-09-22 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anexohistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('anexo_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anexorequerido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
