# Generated by Django 5.2 on 2025-04-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_is_active_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('validador', 'Validador'), ('admin', 'Administrador')], default='usuario', max_length=10),
        ),
    ]
