# Generated by Django 5.0 on 2025-09-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anexousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexohistorico',
            name='trimestre',
        ),
    ]
