# Generated by Django 5.2 on 2025-05-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('validado', '✅ Validado'), ('rechazado', '❌ Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], default='usuario', max_length=10),
        ),
    ]
